[package]
name = "rakkenti/shifters"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
rbxlib = "rakkenti/rbxlib@0.94.4"

# Temp
Knit = "sleitnick/knit@^1.7"
Signal = "sleitnick/signal@1.5.0"
Trove = "sleitnick/trove@0.5.0"