-- shifters@rakken
-- Invasion Game
-- created and maintained by @rakken using rojo and wally
-- Notice: Do not modify any scripts in this place without permission/notice from @rakken,
-- Because Rojo will overwrite them in the next sync
-- Wally is used for my rbxlib library dependency.
-- The source is in a github repository. Let me know if you need the source.
-- Documentation: WIP
